// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://alicguhgkblczzddjvln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsaWNndWhna2JsY3p6ZGRqdmxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NzUzNTUsImV4cCI6MjA2OTU1MTM1NX0.vxL-dub-LDsLDF7BfFssnUBb8uoxFwfz2l-hynCaMGc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});