// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxcboibkwwmflnjirsem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4Y2JvaWJrd3dtZmxuamlyc2VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NjI4NDIsImV4cCI6MjA2OTUzODg0Mn0.x4aWGI8B1r0hRnwucnYMzOfpNYJuVwN-o4RGa7V7LIU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});